package: ypkpathway

before_script:
  - conda update -n root conda
  - conda install binstar binstar-build
  - conda update -n root conda-build
  - conda config --add channels BjornFJohansson

build_targets: conda

script:
  - conda build .



build_targets:
    files: /opt/miniconda/conda-bld/*/*.tar.bz2
    channels: 'main'

after_success:
  - conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p all --output-dir /opt/miniconda/conda-bld/
after_failure:
  - echo Oops?
