package: ypkpathway

before_script:
  - git describe --tags
  - conda update -n root conda
  - conda install anaconda-client anaconda-build
  #- conda update -n root anaconda-build
  - conda update -n root conda-build
  #- cat $CONDARC
  - conda config --add channels https://conda.binstar.org/BjornFJohansson --file $CONDARC
  - cat $CONDARC
  - cat ~/.condarc

iotimeout: 300

#build_targets: conda

script:
  - python setup.py version
  - conda build .

build_targets:
    files: /opt/miniconda/conda-bld/*/*.tar.bz2
    channels: 'main'

after_success:
  - conda convert /opt/miniconda/conda-bld/linux-64/*.tar.bz2 -p all --output-dir /opt/miniconda/conda-bld/
after_failure:
  - echo Oops?
