language: python
python:
  - "2.7"
before_install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
install:
  - pip install -e .
  - python pydna/setup.py version
before_script:
  - pip install coveralls
script:
  - python pydna/setup.py version
#  - nosetests -v -w tests      --with-coverage --with-doctest
#  - nosetests -v -w ypkpathway --with-coverage --with-doctest

deploy:
  provider: pypi
  distributions: "sdist --formats=gztar,zip bdist_wheel"
  user: bjorn
  password:
    secure: "B74QgzwNFATntWfDeIIGQjC49QN2sm17TQnidsOeh4UddC6i0DHjeyqC8BnNyvIZeGcEBfE7rAcK3Q74TAH8PUZnjP3FnK2L1BzqqVeCJU4+RhVUkd2koBPv3Un+zdyKoRI9dPr7TmyTjEEVPyy9esmQYnerXZr5vHjacQy7L10="
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/ypkpathway
