package:
    name: ypkpathway
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  include_recipe: False
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  git_url: .

requirements:
    build:
        - python
        - versioneer
        - pytest
        - pytest-runner
        - ipython
        - nbformat
        - nbconvert
        - pydna
        - docopt
        - notedown
        - pyqt
    run:
        - python
        - ipython
        - nbformat
        - pytest-runner
        - nbconvert
        - pydna
        - docopt
        - notedown
        - pyqt
#test:
#  requires:
#    - pytest
#    - pytest-runner
#  imports:
#    - ypkpathway
#  source_files:
#    - tests
#    - ypkpathway

entry_points:
   - ypkpathway = ypkpathway.gui:main
   - ypkpathway_cli = ypkpathway.ypkpathway:main

about:
  home: https://github.com/BjornFJohansson/ypkpathway
  license: BSD
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.

app:
  entry: ypkpathway
  #icon: icon.png
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.
  type: desk
  own_environment: true

