package:
  name: ypkpathway
build: 
  script: 
    - echo "This is my binstar build with conda"
requirements:
  
  build:
    - python

  run:
    - python

test:
    requires:
        - nose
    commands:
        - python run_tests.py

about:
  summary: This is a binstar build test! 
