package:
  name: ypkpathway
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: .

entry_points:
- ypkpathway = ypkpathway.gui:main
- ypkpathway_cli = ypkpathway.ypkpathway:main

requirements:
  build:
    - python
    - versioneer
    - pytest
    - pytest-runner
    - ipython
    - nbformat
    - nbconvert
    - pydna
    - docopt
    - notedown
    - pyqt
  run:
    - python
    - ipython
    - nbformat
    - nbconvert
    - pydna
    - docopt
    - notedown
    - pyqt
test:
  requires:
    - pyqt
    - pytest
    - pytest-runner
  imports:
    - ypkpathway
  source_files:
    - tests
    - ypkpathway
  commands:
    - echo test
    - echo $GIT_DESCRIBE_TAG
    - echo $GIT_DESCRIBE_NUMBER
    #- ypkpathway_cli -h
    #- ypkpathway_cli -v

about:
  home: https://github.com/BjornFJohansson/ypkpathway
  license: BSD
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.

app:
  entry: ypkpathway
  #icon: icon.png
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.
  type: desk
  own_environment: true

