package:
  name: ypkpathway
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.0') }}

build:
  #preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}

  entry_points:
    - ypkpathway = ypkpathway.gui:main
    - ypkpathway_cli = ypkpathway.ypkpathway:main

requirements:
  build:
    - python
    - ipython
    - pydna
    - docopt
    - notedown
    - pyzmq
  run:
    - python
    - ipython
    - pydna
    - docopt
    - notedown
    - pyqt
    - bsddb
    - pyzmq
test:
  requires:
    - pyqt
    - nose
  commands:
    - echo test
    #- ypkpathway_cli -h
    #- ypkpathway_cli -v

about:
  home: https://github.com/BjornFJohansson/ypkpathway
  license: BSD
  summary: Assemble metabolic pathways from the command line using the ypkpathway protocol

app:
  entry: ypkpathway
  #icon: icon.png
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.
  type: desk
  own_environment: true

