package:
  name: ypkpathway
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  preserve_egg_dir: True
  number: {{environ.get('BINSTAR_BUILD', 1)}}
  entry_points:
    - ypkpathway     = ypkpathway.ypkpathway:main
    - ypkpathway-gui = ypkpathway.gui:main

source:
  path:

requirements:

  build:
    - python
    - pydna
    - docopt
    - notedown

  run:
    - python
    - pydna
    - docopt
    - notedown
    - pyqt

test:
  requires:
    - pyqt
    - nose
  commands:
    #- ypkpathway -h
    #- ypkpathway -v


about:
  home: https://github.com/BjornFJohansson/ypkpathway
  license: BSD
  summary: Assemble metabolic pathways from the command line using the ypkpathway protocol

app:
  entry: ypkpathway-gui
  type: desk
  icon: ypkpathway.png
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.
  #own_environment: true

