package:
  name: ypkpathway
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.1') }}

build:
  #preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

  entry_points:
    - ypkpathway = ypkpathway.gui:main
    - ypkpathway_cli = ypkpathway.ypkpathway:main

requirements:
  build:
    - python ==2.7.10
    - ipython ==3.2.1
    - pydna ==0.9.9
    - docopt ==0.6.2
    - notedown ==1.4.4
    - pyzmq ==14.6.0
    - pyqt ==4.11.3
    #- bsddb

  run:
    - python ==2.7.10
    - ipython ==3.2.1
    - pydna ==0.9.9
    - docopt ==0.6.2
    - notedown ==1.4.4
    - pyzmq ==14.6.0
    - pyqt ==4.11.3
    #- bsddb
test:
  requires:
    - pyqt
    - nose
  commands:
    - echo test
    - echo $GIT_DESCRIBE_TAG
    - echo $GIT_DESCRIBE_NUMBER
    #- ypkpathway_cli -h
    #- ypkpathway_cli -v

about:
  home: https://github.com/BjornFJohansson/ypkpathway
  license: BSD
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.

app:
  entry: ypkpathway
  #icon: icon.png
  summary: Planning of metabolic pathway assembly using the ypkpathway protocol.
  type: desk
  own_environment: true

