# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.2.dev3+g321017b.d20221201'
__version_tuple__ = version_tuple = (3, 0, 2, 'dev3', 'g321017b.d20221201')
